version: '3.6'
services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=core_test
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
