[package]
name = "fn_wasm"
version = "0.1.0"
edition = "2021"

[lib]
name = "fn_wasm"
path = "src/init.rs"
crate-type = ["cdylib", "lib"]

[dependencies]
rustler = "0.26.0"
wasmtime = "1.0.1"
wasmtime-wasi = "1.0.1"
wasi-common = "1.0.1"
